package com.medtrack.auth.soar.model;

import jakarta.persistence.*;
import java.time.Instant;

/**
 * SoarIncidentTicketRecord JPA Entity
 * Represents an Incident Response Ticket automatically generated by SOAR engines
 * under ISO/IEC 27035 Security Incident Management standards.
 */
@Entity
@Table(name = "soar_incident_tickets")
public class SoarIncidentTicketRecord {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false, unique = true)
    private String ticketId;

    @Column(nullable = false)
    private String title;

    @Column(nullable = false)
    private String severity; // CRITICAL, HIGH, MEDIUM, LOW

    @Column(nullable = false)
    private String status; // OPEN, INVESTIGATING, MITIGATED, RESOLVED, CLOSED

    @Column(columnDefinition = "TEXT")
    private String impactedAssetsJson;

    @Column(columnDefinition = "TEXT")
    private String mitigationLogJson;

    @Column(nullable = false)
    private String assignedCommander;

    @Column(nullable = false)
    private Instant createdAt;

    private Instant resolvedAt;

    public SoarIncidentTicketRecord() {}

    public SoarIncidentTicketRecord(String ticketId, String title, String severity,
                                   String impactedAssetsJson, String assignedCommander, Instant createdAt) {
        this.ticketId = ticketId;
        this.title = title;
        this.severity = severity;
        this.status = "OPEN";
        this.impactedAssetsJson = impactedAssetsJson;
        this.mitigationLogJson = "[]";
        this.assignedCommander = assignedCommander;
        this.createdAt = createdAt;
    }

    // Getters and Setters
    public Long getId() { return id; }
    public String getTicketId() { return ticketId; }
    public void setTicketId(String ticketId) { this.ticketId = ticketId; }

    public String getTitle() { return title; }
    public void setTitle(String title) { this.title = title; }

    public String getSeverity() { return severity; }
    public void setSeverity(String severity) { this.severity = severity; }

    public String getStatus() { return status; }
    public void setStatus(String status) { this.status = status; }

    public String getImpactedAssetsJson() { return impactedAssetsJson; }
    public void setImpactedAssetsJson(String impactedAssetsJson) { this.impactedAssetsJson = impactedAssetsJson; }

    public String getMitigationLogJson() { return mitigationLogJson; }
    public void setMitigationLogJson(String mitigationLogJson) { this.mitigationLogJson = mitigationLogJson; }

    public String getAssignedCommander() { return assignedCommander; }
    public void setAssignedCommander(String assignedCommander) { this.assignedCommander = assignedCommander; }

    public Instant getCreatedAt() { return createdAt; }
    public void setCreatedAt(Instant createdAt) { this.createdAt = createdAt; }

    public Instant getResolvedAt() { return resolvedAt; }
    public void setResolvedAt(Instant resolvedAt) { this.resolvedAt = resolvedAt; }
}
