package com.medtrack.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.medtrack.auth.model.User;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.PositiveOrZero;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;
import org.hibernate.annotations.SQLRestriction;

import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * Maintenance Work Order Entity.
 *
 * <p>A MaintenanceTask represents the scheduled maintenance activity,
 * while a MaintenanceWorkOrder represents the operational workflow
 * used by hospital staff and technicians to execute that activity.</p>
 *
 * <p>Supported lifecycle:</p>
 *
 * <pre>
 * OPEN
 *   ↓
 * ASSIGNED
 *   ↓
 * IN_PROGRESS
 *   ↓
 * COMPLETED
 *
 * ASSIGNED / IN_PROGRESS → ON_HOLD
 * ON_HOLD → IN_PROGRESS
 *
 * OPEN / ASSIGNED / IN_PROGRESS / ON_HOLD → CANCELLED
 * </pre>
 */
@Entity
@Table(
        name = "maintenance_work_orders",
        indexes = {
                @Index(name = "idx_work_order_hospital", columnList = "hospital_id"),
                @Index(name = "idx_work_order_status", columnList = "status"),
                @Index(name = "idx_work_order_equipment", columnList = "equipment_id"),
                @Index(name = "idx_work_order_task", columnList = "maintenance_task_id"),
                @Index(name = "idx_work_order_assigned_user", columnList = "assigned_user_id"),
                @Index(name = "idx_work_order_due_date", columnList = "due_date")
        }
)
@SQLRestriction("deleted = false")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class MaintenanceWorkOrder {

    /**
     * Database identifier.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Human-readable unique work-order identifier.
     *
     * <p>Example: WO-000001.</p>
     *
     * <p>Generated by the service layer so callers cannot choose
     * or reuse identifiers.</p>
     */
    @Column(
            name = "work_order_code",
            nullable = false,
            unique = true,
            updatable = false,
            length = 50
    )
    private String workOrderCode;

    /**
     * Hospital owning this work order.
     *
     * <p>This is intentionally stored as a stable ownership key so
     * service-layer authorization can isolate work orders belonging
     * to different hospitals.</p>
     */
    @NotNull(message = "Hospital ID is required")
    @Column(name = "hospital_id", nullable = false)
    private Long hospitalId;

    /**
     * Equipment associated with this work order.
     */
    @NotNull(message = "Equipment is required")
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "equipment_id", nullable = false)
    @JsonIgnore
    @ToString.Exclude
    @EqualsAndHashCode.Exclude
    private Equipment equipment;

    /**
     * Read-only equipment identifier.
     *
     * <p>The Equipment relationship remains the single write path.</p>
     */
    @Column(
            name = "equipment_id",
            insertable = false,
            updatable = false
    )
    private Long equipmentId;

    /**
     * Optional scheduled maintenance task from which this work order
     * originated.
     *
     * <p>A work order may also be created manually, therefore this
     * relationship is nullable.</p>
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "maintenance_task_id")
    @JsonIgnore
    @ToString.Exclude
    @EqualsAndHashCode.Exclude
    private MaintenanceTask maintenanceTask;

    /**
     * Read-only maintenance-task identifier.
     */
    @Column(
            name = "maintenance_task_id",
            insertable = false,
            updatable = false
    )
    private Long maintenanceTaskId;

    /**
     * Short title describing the work order.
     */
    @NotBlank(message = "Title is required")
    @Size(
            max = 255,
            message = "Title must not exceed 255 characters"
    )
    @Column(nullable = false, length = 255)
    private String title;

    /**
     * Detailed description of the maintenance work.
     */
    @Size(
            max = 16000,
            message = "Description must not exceed 16000 characters"
    )
    @Column(columnDefinition = "TEXT")
    private String description;

    /**
     * Type of maintenance being performed.
     */
    @NotNull(message = "Maintenance type is required")
    @Enumerated(EnumType.STRING)
    @Column(
            name = "maintenance_type",
            nullable = false,
            length = 50
    )
    private MaintenanceWorkOrderType maintenanceType;

    /**
     * Priority of the work order.
     */
    @NotNull(message = "Priority is required")
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 30)
    @Builder.Default
    private MaintenanceWorkOrderPriority priority =
            MaintenanceWorkOrderPriority.MEDIUM;

    /**
     * Current lifecycle status.
     */
    @NotNull(message = "Status is required")
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 30)
    @Builder.Default
    private MaintenanceWorkOrderStatus status =
            MaintenanceWorkOrderStatus.OPEN;

    /**
     * Technician assigned to execute the work order.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "assigned_user_id")
    @JsonIgnore
    @ToString.Exclude
    @EqualsAndHashCode.Exclude
    private User assignedUser;

    /**
     * Read-only assigned technician ID.
     */
    @Column(
            name = "assigned_user_id",
            insertable = false,
            updatable = false
    )
    private Long assignedUserId;

    /**
     * API-facing technician name/email.
     *
     * <p>This is retained separately because the existing
     * MaintenanceTask model exposes assignedTechnician as an
     * API-facing string.</p>
     */
    @Size(
            max = 255,
            message = "Assigned technician must not exceed 255 characters"
    )
    @Column(name = "assigned_technician", length = 255)
    private String assignedTechnician;

    /**
     * Date on which work is scheduled to begin.
     */
    @Column(name = "scheduled_date")
    private LocalDate scheduledDate;

    /**
     * Deadline/due date for completing the work order.
     */
    @Column(name = "due_date")
    private LocalDate dueDate;

    /**
     * Actual time at which work began.
     */
    @Column(name = "started_at")
    private LocalDateTime startedAt;

    /**
     * Actual time at which the work order was completed.
     */
    @Column(name = "completed_at")
    private LocalDateTime completedAt;

    /**
     * Time at which the work order was cancelled.
     */
    @Column(name = "cancelled_at")
    private LocalDateTime cancelledAt;

    /**
     * Reason for putting the work order on hold.
     */
    @Size(
            max = 2000,
            message = "Hold reason must not exceed 2000 characters"
    )
    @Column(name = "hold_reason", length = 2000)
    private String holdReason;

    /**
     * Reason for cancelling the work order.
     */
    @Size(
            max = 2000,
            message = "Cancellation reason must not exceed 2000 characters"
    )
    @Column(name = "cancellation_reason", length = 2000)
    private String cancellationReason;

    /**
     * Completion notes entered by the technician.
     */
    @Size(
            max = 16000,
            message = "Completion notes must not exceed 16000 characters"
    )
    @Column(
            name = "completion_notes",
            columnDefinition = "TEXT"
    )
    private String completionNotes;

    /**
     * Total hours spent on the work order.
     */
    @PositiveOrZero(message = "Hours worked cannot be negative")
    @Column(name = "hours_worked")
    private Double hoursWorked;

    /**
     * Parts/materials used during maintenance.
     */
    @Size(
            max = 4000,
            message = "Parts used must not exceed 4000 characters"
    )
    @Column(name = "parts_used", length = 4000)
    private String partsUsed;

    /**
     * Technician signature/evidence.
     */
    @Size(
            max = 60000,
            message = "Signature must not exceed 60000 characters"
    )
    @Column(
            name = "signature",
            columnDefinition = "TEXT"
    )
    private String signature;

    /**
     * Creation timestamp.
     */
    @Column(
            name = "created_at",
            nullable = false,
            updatable = false
    )
    @Builder.Default
    private LocalDateTime createdAt = LocalDateTime.now();

    /**
     * Last modification timestamp.
     */
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    /**
     * User who created the work order.
     */
    @Size(
            max = 255,
            message = "Created by must not exceed 255 characters"
    )
    @Column(name = "created_by", length = 255)
    private String createdBy;

    /**
     * User who last modified the work order.
     */
    @Size(
            max = 255,
            message = "Updated by must not exceed 255 characters"
    )
    @Column(name = "updated_by", length = 255)
    private String updatedBy;

    /**
     * Soft-delete flag.
     *
     * <p>Work orders are never physically deleted because maintenance
     * records are part of the hospital audit trail.</p>
     */
    @Builder.Default
    @Column(
            name = "deleted",
            nullable = false
    )
    private Boolean deleted = false;

    /**
     * Timestamp when the work order was archived.
     */
    @Column(name = "deleted_at")
    private LocalDateTime deletedAt;

    /**
     * User who archived the work order.
     */
    @Size(
            max = 255,
            message = "Deleted by must not exceed 255 characters"
    )
    @Column(name = "deleted_by", length = 255)
    private String deletedBy;

    /**
     * Automatically update the modification timestamp before persistence.
     */
    @PreUpdate
    protected void onUpdate() {
        this.updatedAt = LocalDateTime.now();
    }
}