ALTER TABLE maintenance_tasks
    ADD COLUMN schedule_revision INTEGER DEFAULT 0 NOT NULL;

ALTER TABLE maintenance_tasks
    ADD CONSTRAINT chk_maintenance_schedule_revision
        CHECK (schedule_revision >= 0);

CREATE TABLE maintenance_schedule_revisions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL,
    hospital_id BIGINT NOT NULL,
    revision_number INTEGER NOT NULL,
    actor_user_id BIGINT,
    actor_email VARCHAR(255) NOT NULL,
    reason VARCHAR(1000) NOT NULL,
    changed_fields VARCHAR(255) NOT NULL,
    previous_deadline DATE NOT NULL,
    new_deadline DATE NOT NULL,
    previous_maintenance_type VARCHAR(255) NOT NULL,
    new_maintenance_type VARCHAR(255) NOT NULL,
    previous_description VARCHAR(255),
    new_description VARCHAR(255),
    previous_priority VARCHAR(255) NOT NULL,
    new_priority VARCHAR(255) NOT NULL,
    previous_recurrence_period_days INTEGER,
    new_recurrence_period_days INTEGER,
    amended_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_maintenance_schedule_revision
        UNIQUE (task_id, revision_number),
    CONSTRAINT fk_maintenance_revision_task
        FOREIGN KEY (task_id) REFERENCES maintenance_tasks(id),
    CONSTRAINT fk_maintenance_revision_actor
        FOREIGN KEY (actor_user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT chk_maintenance_revision_number
        CHECK (revision_number > 0),
    CONSTRAINT chk_maintenance_revision_previous_recurrence
        CHECK (previous_recurrence_period_days IS NULL
            OR previous_recurrence_period_days >= 0),
    CONSTRAINT chk_maintenance_revision_new_recurrence
        CHECK (new_recurrence_period_days IS NULL
            OR new_recurrence_period_days >= 0),
    CONSTRAINT chk_maintenance_revision_previous_priority
        CHECK (previous_priority IN ('Normal', 'High', 'Critical')),
    CONSTRAINT chk_maintenance_revision_new_priority
        CHECK (new_priority IN ('Normal', 'High', 'Critical'))
);

CREATE INDEX idx_maintenance_revision_task_timeline
    ON maintenance_schedule_revisions(task_id, hospital_id, revision_number);
CREATE INDEX idx_maintenance_revision_hospital_time
    ON maintenance_schedule_revisions(hospital_id, amended_at);

ALTER TABLE maintenance_task_activities
    DROP CONSTRAINT chk_maintenance_activity_type;

ALTER TABLE maintenance_task_activities
    ADD CONSTRAINT chk_maintenance_activity_type CHECK (event_type IN (
        'TASK_CREATED',
        'TECHNICIAN_ASSIGNED',
        'TECHNICIAN_REASSIGNED',
        'STATUS_CHANGED',
        'WORK_DETAILS_UPDATED',
        'SCHEDULE_AMENDED',
        'TASK_ARCHIVED'
    ));
