-- Decommissioning / disposal workflow (issue #744).
-- Assets are never silently deleted: a disposal record documents the method and reason, the
-- manager approval, the data-sanitisation confirmation and the certificate of disposal.

CREATE TABLE IF NOT EXISTS equipment_disposals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipment_id BIGINT NOT NULL,
    hospital_id BIGINT NOT NULL,
    disposal_method VARCHAR(40) NOT NULL,
    disposal_reason CLOB,
    effective_date DATE,
    stores_patient_data BOOLEAN NOT NULL DEFAULT FALSE,
    data_sanitization_confirmed BOOLEAN NOT NULL DEFAULT FALSE,
    data_sanitization_details CLOB,
    data_sanitized_at TIMESTAMP,
    data_sanitized_by VARCHAR(255),
    status VARCHAR(40) NOT NULL,
    certificate_number VARCHAR(40),
    notes CLOB,
    requested_by VARCHAR(255) NOT NULL,
    approved_by VARCHAR(255),
    rejected_by VARCHAR(255),
    rejected_reason CLOB,
    completed_by VARCHAR(255),
    cancelled_by VARCHAR(255),
    requested_at TIMESTAMP NOT NULL,
    approved_at TIMESTAMP,
    rejected_at TIMESTAMP,
    completed_at TIMESTAMP,
    cancelled_at TIMESTAMP,
    CONSTRAINT fk_equipment_disposal_equipment FOREIGN KEY (equipment_id) REFERENCES equipment(id)
);

CREATE INDEX IF NOT EXISTS idx_equipment_disposal_equipment ON equipment_disposals (equipment_id, hospital_id, requested_at);
CREATE INDEX IF NOT EXISTS idx_equipment_disposal_status ON equipment_disposals (hospital_id, status, requested_at);
CREATE INDEX IF NOT EXISTS idx_equipment_disposal_certificate ON equipment_disposals (certificate_number);
