ALTER TABLE equipment ADD COLUMN IF NOT EXISTS room_location VARCHAR(100);
ALTER TABLE equipment ADD COLUMN IF NOT EXISTS ward_location VARCHAR(100);
ALTER TABLE equipment ADD COLUMN IF NOT EXISTS custodian VARCHAR(255);
ALTER TABLE equipment ADD COLUMN IF NOT EXISTS location_effective_date DATE;
ALTER TABLE equipment ADD COLUMN IF NOT EXISTS replacement_equipment_id BIGINT;

CREATE TABLE IF NOT EXISTS equipment_lifecycle_actions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipment_id BIGINT NOT NULL,
    hospital_id BIGINT NOT NULL,
    action_type VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL,
    previous_department VARCHAR(255),
    new_department VARCHAR(255),
    room_location VARCHAR(100),
    ward_location VARCHAR(100),
    custodian VARCHAR(255),
    effective_date DATE,
    replacement_equipment_id BIGINT,
    depreciation_amount DECIMAL(14, 2),
    notes CLOB,
    requested_by VARCHAR(255) NOT NULL,
    approved_by VARCHAR(255),
    rejected_by VARCHAR(255),
    rejected_reason CLOB,
    completed_by VARCHAR(255),
    cancelled_by VARCHAR(255),
    requested_at TIMESTAMP NOT NULL,
    approved_at TIMESTAMP,
    rejected_at TIMESTAMP,
    completed_at TIMESTAMP,
    cancelled_at TIMESTAMP,
    CONSTRAINT fk_equipment_lifecycle_equipment FOREIGN KEY (equipment_id) REFERENCES equipment(id),
    CONSTRAINT fk_equipment_lifecycle_replacement FOREIGN KEY (replacement_equipment_id) REFERENCES equipment(id)
);

CREATE INDEX IF NOT EXISTS idx_equipment_lifecycle_equipment ON equipment_lifecycle_actions (equipment_id, hospital_id, requested_at);
CREATE INDEX IF NOT EXISTS idx_equipment_lifecycle_status ON equipment_lifecycle_actions (hospital_id, status, requested_at);
